/*
 * This file was generated by the Gradle 'init' task.
 */
 
// add application plugin
plugins {
    application
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.antlr.antlr4.runtime)
    api(libs.org.antlr.antlr4.maven.plugin)
    api(libs.com.google.code.gson.gson)
    api(libs.commons.io.commons.io)
    api(libs.com.github.julianthome.autorex)
    api(libs.com.alibaba.fastjson)
    api(libs.commons.cli.commons.cli)
    api(libs.org.prefuse.prefuse)
    api(libs.org.javatuples.javatuples)
}

group = "cn.ac.ios"
version = "1.0.0"
description = "ReDoSHunter"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

application {
    mainClass = "cn.ac.ios.Test"
}